-- Supabase replacement for the former local SQLite gameplay database.

create table public.learning_words (
  id bigint generated by default as identity primary key,
  expression text not null unique,
  reading text not null,
  meaning text not null,
  topic text,
  level text,
  state integer not null default 0 check (state between 0 and 3),
  stability double precision not null default 0,
  difficulty double precision not null default 0,
  lapses integer not null default 0,
  reps integer not null default 0,
  last_review_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.learning_review_logs (
  id bigint generated always as identity primary key,
  word_id bigint not null references public.learning_words(id) on delete cascade,
  rating integer not null check (rating between 1 and 4),
  state integer not null check (state between 0 and 3),
  elapsed_ms integer,
  review_datetime timestamptz not null default now()
);

create table public.learning_word_embeddings (
  word_id bigint primary key references public.learning_words(id) on delete cascade,
  embedding jsonb not null
);

create table public.game_countries (
  code text primary key,
  name text not null unique,
  flag text not null,
  latitude double precision not null,
  longitude double precision not null,
  display_order smallint not null default 0,
  character_type text not null,
  character_icon text not null,
  character_story text not null,
  character_gradient text not null,
  created_at timestamptz not null default now()
);

create table public.game_scenarios (
  id text primary key,
  country_code text not null references public.game_countries(code) on delete cascade,
  title text not null,
  icon text not null,
  description text not null,
  is_special boolean not null default false,
  display_order smallint not null default 0,
  status text not null default 'locked' check (status in ('locked', 'unlocked', 'completed')),
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.game_scenario_vocabulary (
  scenario_id text not null references public.game_scenarios(id) on delete cascade,
  display_order smallint not null,
  english text not null,
  chinese text not null,
  pinyin text not null,
  primary key (scenario_id, display_order)
);

create table public.backend_user_state (
  id smallint primary key default 1 check (id = 1),
  tokens bigint not null default 100 check (tokens >= 0),
  unlocked_countries jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table public.game_settings (
  key text primary key,
  value jsonb not null
);

alter table public.learning_words enable row level security;
alter table public.learning_review_logs enable row level security;
alter table public.learning_word_embeddings enable row level security;
alter table public.game_countries enable row level security;
alter table public.game_scenarios enable row level security;
alter table public.game_scenario_vocabulary enable row level security;
alter table public.backend_user_state enable row level security;
alter table public.game_settings enable row level security;

-- These tables are intentionally server-only. The service role bypasses RLS; no
-- browser policies are created. The Express API remains the sole public interface.

create or replace function public.backend_spend_tokens(p_amount bigint)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_amount <= 0 then
    raise exception 'Amount must be greater than zero' using errcode = '22023';
  end if;
  update public.backend_user_state
  set tokens = tokens - p_amount, updated_at = now()
  where id = 1 and tokens >= p_amount;
  if not found then
    raise exception 'Insufficient tokens' using errcode = 'P0001';
  end if;
  return true;
end;
$$;

create or replace function public.backend_earn_tokens(p_amount bigint)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare new_balance bigint;
begin
  if p_amount <= 0 then
    raise exception 'Amount must be greater than zero' using errcode = '22023';
  end if;
  update public.backend_user_state
  set tokens = tokens + p_amount, updated_at = now()
  where id = 1 returning tokens into new_balance;
  return new_balance;
end;
$$;

create or replace function public.backend_unlock_country(p_country_name text, p_cost bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  state public.backend_user_state%rowtype;
  countries jsonb;
begin
  select * into state from public.backend_user_state where id = 1 for update;
  if state.tokens < p_cost then
    raise exception 'Insufficient tokens' using errcode = 'P0001';
  end if;
  countries := state.unlocked_countries;
  if not countries @> jsonb_build_array(p_country_name) then
    countries := countries || jsonb_build_array(p_country_name);
  end if;
  update public.backend_user_state
  set tokens = state.tokens - p_cost,
      unlocked_countries = countries,
      updated_at = now()
  where id = 1;
  return jsonb_build_object(
    'tokens', state.tokens - p_cost,
    'unlockedCountries', countries
  );
end;
$$;

create or replace function public.reset_backend_state()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  truncate table public.learning_review_logs restart identity;
  truncate table public.learning_word_embeddings;
  update public.learning_words set
    state = 0, stability = 0, difficulty = 0, lapses = 0, reps = 0,
    last_review_at = null;
  update public.game_scenarios set status = 'locked', completed_at = null;
  update public.game_scenarios set status = 'unlocked' where id = 'street-market';
  insert into public.backend_user_state (id, tokens, unlocked_countries)
  values (1, 100, '[]'::jsonb)
  on conflict (id) do update set
    tokens = excluded.tokens,
    unlocked_countries = excluded.unlocked_countries,
    updated_at = now();
end;
$$;

revoke all on function public.backend_spend_tokens(bigint) from public, anon, authenticated;
revoke all on function public.backend_earn_tokens(bigint) from public, anon, authenticated;
revoke all on function public.backend_unlock_country(text, bigint) from public, anon, authenticated;
revoke all on function public.reset_backend_state() from public, anon, authenticated;
grant execute on function public.backend_spend_tokens(bigint) to service_role;
grant execute on function public.backend_earn_tokens(bigint) to service_role;
grant execute on function public.backend_unlock_country(text, bigint) to service_role;
grant execute on function public.reset_backend_state() to service_role;
