-- User economy and progression data for Langtour.
-- Run with `supabase db push`, or paste this migration into the Supabase SQL editor.

create table public.levels (
  id smallint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  minimum_xp bigint not null default 0 check (minimum_xp >= 0),
  display_order smallint not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.ranks (
  id smallint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  minimum_xp bigint not null default 0 check (minimum_xp >= 0),
  display_order smallint not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  tokens bigint not null default 100 check (tokens >= 0),
  experience_points bigint not null default 0 check (experience_points >= 0),
  level_id smallint references public.levels(id) on delete set null,
  rank_id smallint references public.ranks(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.login_history (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  logged_in_at timestamptz not null default now(),
  auth_provider text,
  created_at timestamptz not null default now()
);

create index login_history_user_logged_in_idx
  on public.login_history (user_id, logged_in_at desc);

alter table public.levels enable row level security;
alter table public.ranks enable row level security;
alter table public.profiles enable row level security;
alter table public.login_history enable row level security;

create policy "Authenticated users can view active levels"
  on public.levels for select to authenticated using (is_active);
create policy "Authenticated users can view active ranks"
  on public.ranks for select to authenticated using (is_active);
create policy "Users can view their own profile"
  on public.profiles for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "Users can view their own login history"
  on public.login_history for select to authenticated
  using ((select auth.uid()) = user_id);

-- Trusted Auth triggers create profiles and login records. Clients cannot forge them.
create or replace function public.handle_auth_user_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.profiles (user_id) values (new.id)
    on conflict (user_id) do nothing;

    if new.last_sign_in_at is not null then
      insert into public.login_history (user_id, logged_in_at, auth_provider)
      values (new.id, new.last_sign_in_at, new.raw_app_meta_data ->> 'provider');
    end if;
  elsif new.last_sign_in_at is distinct from old.last_sign_in_at
    and new.last_sign_in_at is not null then
    insert into public.login_history (user_id, logged_in_at, auth_provider)
    values (new.id, new.last_sign_in_at, new.raw_app_meta_data ->> 'provider');
  end if;

  return new;
end;
$$;

create trigger on_auth_user_change
  after insert or update of last_sign_in_at on auth.users
  for each row execute function public.handle_auth_user_change();

create or replace function public.set_profile_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_profile_updated_at();

-- Atomically spend tokens for the current user and return the new balance.
create or replace function public.spend_tokens(amount bigint)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_balance bigint;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;
  if amount <= 0 then
    raise exception 'Amount must be greater than zero' using errcode = '22023';
  end if;

  update public.profiles
  set tokens = tokens - amount
  where user_id = (select auth.uid()) and tokens >= amount
  returning tokens into new_balance;

  if new_balance is null then
    raise exception 'Insufficient tokens' using errcode = 'P0001';
  end if;
  return new_balance;
end;
$$;

revoke all on function public.spend_tokens(bigint) from public;
grant execute on function public.spend_tokens(bigint) to authenticated;

-- Backfill users who existed before this migration.
insert into public.profiles (user_id)
select id from auth.users
on conflict (user_id) do nothing;
